import jsPDF from 'jspdf';
import { calculateHealthScore, getHealthRating } from './healthScore';
import { formatDate } from './formatDate';

/**
 * Generate PDF report from audit data
 * @param {Object} data - Audit data from API
 * @returns {jsPDF} - PDF document
 */
export function generatePDF(data) {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  // Colors
  const primaryColor = [0, 212, 255]; // Electric Blue
  const secondaryColor = [124, 58, 237]; // Purple
  const textColor = [255, 255, 255];
  const bgColor = [7, 9, 15]; // Background
  
  // Background
  pdf.setFillColor(...bgColor);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');
  
  // Header gradient effect
  pdf.setFillColor(...primaryColor);
  pdf.rect(0, 0, pageWidth, 40, 'F');
  
  // Logo and title
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Page Pulse', 20, 25);
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text('AI Website Auditor', pageWidth - 20, 25, { align: 'right' });
  
  // Date
  pdf.setTextColor(150, 150, 150);
  pdf.setFontSize(9);
  pdf.text(`Generated: ${formatDate(data.timestamp)}`, 20, 50);
  
  // Website URL
  pdf.setTextColor(...primaryColor);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Website', 20, 65);
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  const urlLines = pdf.splitTextToSize(data.url, pageWidth - 40);
  pdf.text(urlLines, 20, 75);
  
  // Health Score
  const healthScore = calculateHealthScore(data);
  const healthRating = getHealthRating(healthScore);
  
  pdf.setTextColor(...primaryColor);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Health Score', 20, 100);
  
  pdf.setTextColor(...primaryColor);
  pdf.setFontSize(28);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`${healthScore}/100`, 20, 115);
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text(healthRating, 70, 115);
  
  // Statistics
  let yPos = 135;
  const stats = [
    { label: 'HTTP Status', value: data.httpStatus },
    { label: 'Response Time', value: data.responseTime },
    { label: 'Page Title', value: data.pageTitle },
    { label: 'H1 Tags', value: data.h1Count },
    { label: 'Images Missing ALT', value: data.imagesMissingAlt },
    { label: 'Word Count', value: data.wordCount.toLocaleString() }
  ];
  
  pdf.setTextColor(...secondaryColor);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Statistics', 20, yPos);
  yPos += 10;
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  
  stats.forEach((stat, index) => {
    pdf.text(`${stat.label}:`, 20, yPos);
    pdf.text(String(stat.value), 80, yPos);
    yPos += 8;
  });
  
  // Meta Description
  yPos += 5;
  pdf.setTextColor(...secondaryColor);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Meta Description', 20, yPos);
  yPos += 10;
  
  pdf.setTextColor(200, 200, 200);
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  const metaLines = pdf.splitTextToSize(
    data.metaDescription || 'No meta description found',
    pageWidth - 40
  );
  pdf.text(metaLines, 20, yPos);
  
  // Footer
  pdf.setTextColor(100, 100, 100);
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.text(
    'Generated by Page Pulse - Built for Digital Heroes Training Task',
    pageWidth / 2,
    pageHeight - 15,
    { align: 'center' }
  );
  
  return pdf;
}

/**
 * Download PDF report
 * @param {Object} data - Audit data from API
 */
export function downloadPDF(data) {
  try {
    const pdf = generatePDF(data);
    const fileName = `page-pulse-audit-${new Date().getTime()}.pdf`;
    pdf.save(fileName);
    return true;
  } catch (error) {
    console.error('Failed to generate PDF:', error);
    return false;
  }
}
